# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Crownicles - A multiplayer role-play game for Discord
email: contact@crownicles.com
description: >-
  Crownicles is an open-source Discord bot based on a multiplayer text adventure game. 
  Begin your journey in a medieval world and battle to win the kingdom's princess's hand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crownicles.com" # the base hostname & protocol for your site
twitter_username: Bastlast_
github_username:  Crownicles

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Ensure assets are properly included
include:
  - public
  - static

# Keep original structure
keep_files:
  - public
  - static

# Make sure asset paths work correctly
permalink: pretty
sass:
  style: compressed
